### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by rupertraphael** [agileware/au.com.agileware.renewalinvoices#1]
Hi,

Is there any initial setup that I need to do to get this extension to work? Like maybe enable invoicing under the CiviContribute Component Settings?

I'm asking because I'm getting the following errors when I run the scheduled reminders job :
<img width="1282" alt="Screen Shot 2020-09-26 at 11 00 01 PM" src="https://user-images.githubusercontent.com/19609578/94356461-226cc400-004c-11eb-86fa-3ffd784b50c4.png">

Also, @agileware-justin, thank you for sharing your extension over at the CiviCRM Mattermost chatroom.

Cheers!
Rupert

**Comment by rupertraphael** [comment]
Update: So I guess, those errors are due to the fact that I didn't add your custom tokens to my template.

But now, I'm getting this:
<img width="1425" alt="Screen Shot 2020-09-26 at 11 15 41 PM" src="https://user-images.githubusercontent.com/19609578/94356668-34e7fd00-004e-11eb-8b1b-03e06e4a8fc5.png">
**Error message: contribution_recur_contribution_status_id is not a valid integer**

I've tried editing line 437 of `CRM/RenewalInvoices/BAO/RenewalInvoice.php` by changing `Pending` to 2 as follows:
<img width="1141" alt="Screen Shot 2020-09-26 at 11 17 16 PM" src="https://user-images.githubusercontent.com/19609578/94356702-6e206d00-004e-11eb-9a20-a87d7192afe7.png">

But it looks like this is not causing the problem.

Anyway, if you can't think of anything that's causing the problem I guess it could be the because I'm using version 5.22 of Civi or because of any conflict with other extensions.

**Comment by edward-peters** [comment]
@rupertraphael  Did you manage to get this extension working? I cannot figure it out from the ReadMe.

**Comment by agileware-justin** [comment]
Sorry guys, we thought this extension would be a good idea. Just didn't work out that way.
